import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {CookieConsent} from "@/components/ui/CookieConsent";
import {Footer} from "@/components/layout/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ro">
        <head>
            <Script
                async
                src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5072803047179041"
                crossOrigin="anonymous"
                strategy="afterInteractive"
            />
            <meta name="google-adsense-account" content="ca-pub-5072803047179041"/>
        </head>
        <body>
        {children}
        <Footer/>
        <CookieConsent />
        </body>
        </html>
    );
}
